---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fileshare
  labels:
    app: fileshare
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: default
